### PR TITLE
Fix deployment workflows + parameterize docs

### PR DESCRIPTION
**Pull request by MichaelDeng03**
- Update docs docker container build site
- Move docs into `webapp` directory, following the same structure as all other services 

Misc:
- Delete `webapp/uv.lock` that didn't have an associated `pyproject.toml`
- Delete dind-builder
- Update AWS Tool Listener rule creator to respect existing priorities
  - Motivation: When deploying multiple services at the same time, they would calculate the same lowest available priority simultaneously, which would then conflict later.

### CODE REVIEW

**Review by kgang — APPROVED** [review]
What is the fix?

**Comment by MichaelDeng03** [comment]
Docs made it to the original deployment workflows, when it shouldn't have. I updated the docs builds so that it works on the deploy to staging workflows instead of removing it.

**Comment by MichaelDeng03** [comment]
ahhhh gosh dangit I keep on forgetting to do things

**Comment by MichaelDeng03** [comment]
docs deployment is duped :sob:  in deploy to staging and in deploy docs

**Comment by kgang** [comment]
no worries, I think we need to upgrade our task management tools

**Comment by kgang** [comment]
maybe :sparkles: ai-generated:sparkles:

**Comment by MichaelDeng03** [comment]
wdym by task management?

**Comment by kgang** [comment]
a jira-like or using github projects + issues

**Comment by MichaelDeng03** [comment]
Ahhh yeah I agree

**Comment by kgang** [comment]
maybe linearb, people say they like that a lot

**Comment by MichaelDeng03** [comment]
omg I'm sorry, I found another issue - I copied the prod deployment from staging, so the prod workflow is deploying to staging instead

**Comment by MichaelDeng03** [comment]
up to you, i'm not sure what the point would be

**Comment by kgang** [comment]
we should keep them updated on how we're using the product

**Comment by MichaelDeng03** [comment]
makes sense

**Comment by kgang** [comment]
i can ping them

**Pull request merged**
