### PR TITLE
Michael/fix tests

### PR DESCRIPTION
**Pull request by MichaelDeng03**

### CODE REVIEW

**Comment by kgang** [comment]
Might need to look at these later michael, suppressing it for now
```
src/concrete-core/concrete/tools/aws.py:81: error: Type of TypedDict is ambiguous, none of ("ContainerDefinitionTypeDef", "ContainerDefinitionOutputTypeDef") matches cleanly  [misc]
src/concrete-core/concrete/tools/aws.py:81: error: List comprehension has incompatible type List[dict[str, object]]; expected List[ContainerDefinitionTypeDef | ContainerDefinitionOutputTypeDef]  [misc]
src/concrete-core/concrete/tools/aws.py:263: error: Type of TypedDict is ambiguous, none of ("ContainerDefinitionTypeDef", "ContainerDefinitionOutputTypeDef") matches cleanly  [misc]
src/concrete-core/concrete/tools/aws.py:263: error: List comprehension has incompatible type List[dict[str, object]]; expected List[ContainerDefinitionTypeDef | ContainerDefinitionOutputTypeDef]  [misc]
src/concrete-core/concrete/tools/aws.py:319: error: Incompatible types (expression has type "tuple[str, bool]", TypedDict item "targetGroupArn" has type "str")  [typeddict-item]
```

**Comment by MichaelDeng03** [comment]
Okay. I wonder how these didn't show up in the past.

**Comment by kgang** [comment]
I had to install boto3 stubs

**Comment by kgang** [comment]
it's added now in the workspace deps

**Pull request merged**
