### PR TITLE
New landing page, basic version one

### PR DESCRIPTION
**Pull request by abjjabjj**
Can try to run `make local-homepage` but I think it doesn't work without `fastapi[standard]` as a dev dependency in the root directory.

There's minimal to no styling at the moment. I'd like to at least get some basic colors and really make the CTA eye-catching before publishing a basic version.

### CODE REVIEW

**Comment by kgang** [comment]
Nice first pass!! :fire: :fire: <!subteam^S07SKMS37QU> please work with andy to improve. My thoughts

- feels unbalanced (maybe the "who are we?" and the text after is a little smaller
- yellow github link is ugly

**Comment by MichaelDeng03** [comment]
The solution I had for your `fastapi[standard]` problem was to stick a pyproject.toml into `webapp/`, and then add `webapp` as as a workspace member. Then, add `fastapi[standard]` to common webapp deps. 
The expectation then, is that all webapps share a common webapp project, and they can add whatever they want to their own deps. This requires updating a ton of docker images ( which I have done on my jaime branch). 

Alternatively, you can add `webapp/homepage` to your root workspace members, and update the `webapp/homepage/pyproject.toml` to use `fastapi[standard]` instead of raw `fastapi`.

**Comment by MichaelDeng03** [comment]
I don't see a github link - but I agree that yellow is ugly
IMO the slogan "ushering in the age...." is too aspirational and incongruous with the rawdogged static html and css.
Contact Us linking to email directly is a cool touch

[Slack File: image.png](https://files.slack.com/files-pri/T07DSK6AKDJ-F0851NZ2D8R/image.png)

**Comment by abjjabjj** [comment]
Do you guys think the yellow would still be ugly if the background was purple/violet?

**Comment by MichaelDeng03** [comment]
could you post a ss?

**Comment by kgang** [comment]
Idk about messing with other people's logos personally. I think if it's coherent, like a lot of things are gonna be yellow it could be ok. Please ignore my feelings tho if desired

**Comment by abjjabjj** [comment]
[Slack File: image.png](https://files.slack.com/files-pri/T07DSK6AKDJ-F084LLB6TDK/image.png)

**Comment by MichaelDeng03** [comment]
yellow on purple looks okay, but i'm not sure that I like purple as a background color in general. maybe if it were more of a regal purple?

**Comment by abjjabjj** [comment]
[Slack File: image.png](https://files.slack.com/files-pri/T07DSK6AKDJ-F0852763Q6M/image.png)

**Comment by MichaelDeng03** [comment]
final decision is up to you, but I'm personally not a fan

**Comment by abjjabjj** [comment]
just not a fan of purple in general?

**Comment by MichaelDeng03** [comment]
yeah, it doesn't feel very professional

**Comment by abjjabjj** [comment]
how about this color

[Slack File: image.png](https://files.slack.com/files-pri/T07DSK6AKDJ-F085CBR1SAU/image.png)

**Comment by MichaelDeng03** [comment]
I think I'm just boring and prefer white/gray/black.
But I also don't have a single creative bone, so if you see the vision, go for it.

**Comment by abjjabjj** [comment]
Hmmmm I'll cook up one primarily grayscale version and one primarily colored version then

**Comment by abjjabjj** [comment]
I'll leave it alone here then and if there are problems with the flow after jaime is merged then we can fix it

**Comment by MichaelDeng03** [comment]
Sounds good. This is the solution that I settled on in jaime
<https://abstractoperators.slack.com/archives/C07E3HJJQFK/p1734020659844309>

**Comment by abjjabjj** [comment]
[Slack File: Screen Recording 2024-12-13 at 15.52.14.mov](https://files.slack.com/files-tmb/T07DSK6AKDJ-F0850MT9VKP-81fdac4d81/screen_recording_2024-12-13_at_15.52.14.mp4)

**Comment by kgang** [comment]
oh, hover effect..??

**Comment by abjjabjj** [comment]
yeah

**Comment by abjjabjj** [comment]
thoughts?

**Comment by kgang** [comment]
I liked it haha

**Comment by abjjabjj** [comment]
[Slack File: Screen Recording 2024-12-13 at 15.58.35.mov](https://files.slack.com/files-tmb/T07DSK6AKDJ-F085G876CDP-fe7a35b203/screen_recording_2024-12-13_at_15.58.35.mp4)

**Comment by MichaelDeng03** [comment]
Looks really good!
My version is still blue/yellow, not sure why I don't see the new gray/purple.

I'm beginning to see the color scheme vision.
There's still some dissonance between yellow github and the purple/orange contact us. I feel that they are too vibrant as well.
The color changing when you hover is a really cool touch.
Potential idea: Glimmering gray background.

I think the nav bar should probably be fixed as you scroll.

Have you considered how this looks on a phone? I think Kent will potentially be sharing this homepage with people at networking events, so phone viewing might be important. @kgang can you confirm?

**Comment by kgang** [comment]
Thanks for the ping, yes phone is important for practical purposes. The flow usually goes
- Rando asks what I do or they know I'm a founder
- They ask what I'm working on/how it's been going
- If they're interested, they'll ask to see the website
So people who are looking at our website are already inclined to be on our side. The need the website should fill is
- show that we can have a cool/aesthetic website
- describe what we do and what we've done
- give a place for someone to look at in the future to contact us or learn more about us
Additionally, I'll be sending this as part of a cold outbound (maybe in my email signature too?) so less friendly randos will also look at it wondering how legit we are

**Comment by abjjabjj** [comment]
I haven't taken a look at phone yet, but good catch. The gray/purple wasn't pushed, I just did a quick switcheroo for the screencap. Do you prefer that color scheme <!subteam^S07SKMS37QU>?


Will fix the nav bar and change up the colors for github/contact us

**Comment by MichaelDeng03** [comment]
i do prefer it

**Comment by kgang** [comment]
I wonder if we really even need people to contact us lol. Wondering also if they do need to contact us if my calendly is better. Sorry, this isn't the most helpful lol

**Comment by abjjabjj** [comment]
What's the alternative? Are you saying that in all realistic cases we'd be the ones initiating contact anyways?

**Comment by kgang** [comment]
I guess we should just grab people's emails + company to reach out to them later if they want to work with us

**Comment by kgang** [comment]
I think three clients could carry us quite far

**Comment by abjjabjj** [comment]
That makes sense. Idk if that means we don't include a way to contact us on the landing page though

**Comment by kgang** [comment]
yeah you know ig it'd be fine for now to manage all inbound manually until it becomes too much

**Comment by abjjabjj** [comment]
Calendly is a good idea though

**Comment by kgang** [comment]
[calendly.com/kentgang/30min](http://calendly.com/kentgang/30min)

**Comment by abjjabjj** [comment]
Aw dang I was hoping you could write a message with calendly too

**Comment by abjjabjj** [comment]
Jk you can

**Comment by abjjabjj** [comment]
Nice

**Comment by kgang** [comment]
yeah there's a spot to add additional context

**Comment by kgang** [comment]
I could create different calendly links for different meeting types too if I pay for calendly but probably not for now

**Comment by abjjabjj** [comment]
Yeah just the one is fine

**Comment by MichaelDeng03** [comment]
lmk if you need any help with deploying it :+1:

**Comment by abjjabjj** [comment]
probably will

**Comment by abjjabjj** [comment]
Forgot to open contact us, but it goes to calendly now

[Slack File: Screen Recording 2024-12-17 at 14.42.38.mov](https://files.slack.com/files-tmb/T07DSK6AKDJ-F08683DML8G-4bfca681b4/screen_recording_2024-12-17_at_14.42.38.mp4)

**Comment by MichaelDeng03** [comment]
i think the top text should be centered not left justified

**Comment by MichaelDeng03** [comment]
looks good tho

**Comment by abjjabjj** [comment]
How about this?

[Slack File: Screen Recording 2024-12-17 at 14.54.48.mov](https://files.slack.com/files-tmb/T07DSK6AKDJ-F085CM1QD6J-0987bc8447/screen_recording_2024-12-17_at_14.54.48.mp4)

**Comment by MichaelDeng03** [comment]
yeah I think that looks better

**Comment by abjjabjj** [comment]
kk i need to run an errand rq but if you wanna approve i can be back in 30 to merge/deploy

**Review by MichaelDeng03 — CHANGES_REQUESTED** [review]
Could you remove the dag stuff? I think it's only `dag_project.py` and `api/server.py`. 
Otherwise, LGTM

**Comment by MichaelDeng03** [comment]
I'll probably won't be around in 30, GL

**Comment by abjjabjj** [comment]
I rebased the entire branch onto main because it original branched off of the project api branches

**Comment by kgang** [comment]
:eyes:

**Comment by abjjabjj** [comment]
if you wanna approve i believe i addressed the changes

**Comment by kgang** [comment]
Let's wait til Michael is on tmw. Request change should mean that you'd like to be blocking

**Comment by kgang** [comment]
I'll ask him though if that was necessary

**Comment by abjjabjj** [comment]
sg

**Review by MichaelDeng03 — APPROVED** [review]
lgtm!

**Comment by abjjabjj** [comment]
I'll check PR descriptions from now on

**Pull request merged**
