### PR TITLE
Created SoftwareProjectWorker to consume prompts and instantiate soft…

### PR DESCRIPTION
**Pull request by abjjabjj**
…ware projects, i.e. orchestrator is now only responsible for submitting prompts to message queue aka sql db. orchestrator submits prompts asyncly, softwareprojectworkers should be run using run() as a coroutine

### CODE REVIEW

**Comment by abjjabjj** [comment]
@kgang `SoftwareProjectWorker` has `multiprocess ` builtin, but not `SoftwareOrchestrator`. I feel like `asyncio` would be a better fit for it because it's mainly I/O bound waiting for the workers to finish their results. Let's talk about it tomorrow.

@MichaelDeng03 probably good for you to take a look at this too because it changes how `SoftwareProjects` are processed.

**Comment by kgang** [comment]
Ok I'll take a look tonight but that makes sense

**Comment by kgang** [comment]
should we keep this up or :hocho: ?

**Comment by abjjabjj** [comment]
deadge

**Comment by abjjabjj** [comment]
it's not going to make it chief. i'll probably just use it as a reference for a bit

**Comment by abjjabjj** [comment]
Not worth merging in/continuing work on due to upcoming implementation of messaging queue/async workers. Will keep for the time being as a reference.

**Pull request closed without merging**
