### PR TITLE
Michael/tooluse

### PR DESCRIPTION
**Pull request by MichaelDeng03**
- Dynamically replace response_format with original response_format + Tool
- Update invoke_tool to take a Tool object
- Fix SQLModelOperator.to_obj
- Provide Operators invoke_tool as a instance method
- Call tools under the hood of qna to use tool context to answer the original query.

### CODE REVIEW

**Review by kgang — APPROVED** [review]
Stepped through commit by commit, thanks for keeping the git history clean

Unfortunate the tool call is blocking, medium prio to asynkify that

Interesting use case we enable is having state on the tool since we have instance methods not static methods on tools:)

**Comment by MichaelDeng03** [comment]
Thanks for noticing the git history, i've been using vscode source control lately, and it's been a lot easier to track changes vs. hitting it with a `git commit -am ''`
Tool state could be nice, I imagine Operators would have to keep track of their own tool instance then.

**Comment by kgang** [comment]
Oh I thought we assigned tool instances to operators is it tool classes?

**Comment by MichaelDeng03** [comment]
class type only

**Comment by MichaelDeng03** [comment]
:man-facepalming: i didn't change the pr title before mergign

**Pull request merged**
