### PR TITLE
AbstractOperator Base Class, ConcreteBaseModel, Celery integration

### PR DESCRIPTION
**Pull request by abjjabjj**
- Create single celery supertask called `abstract_operation` through which all operations will route through
 - Lots of new pydantic models for the sake of serialization and consistent data objects
- Refactor `concrete` operators to inherit from `AbstractOperator` base class
- Create `MetaAbstractOperator` metaclass to facilitate creation of operators
  - new operations (class methods) added onto operators will automatically be wrapped in the prompt engineering function `qna`
  - operations will also have attached methods that mirror those for a typical celery task
    - currently only `delay` is implemented
- Introduced `use_celery` flag to `orchestrator` to split execution based on user preference
  - TODO: Implement celery version of existing `SoftwareProject` workflow
- Left TODOs where needed. They weren't exactly necessary for the functionality but would improve future development

### CODE REVIEW

**Comment by kgang** [comment]
test test

**Comment by abjjabjj** [comment]
test

**Comment by abjjabjj** [comment]
Looks like comments on GH show up on axolo

**Comment by kgang** [comment]
Merging this so we can look at https://github.com/abstractoperators/concrete/pull/27 in its entirety
May not merge https://github.com/abstractoperators/concrete/pull/27 ultimately

**Pull request merged**
