### PR TITLE
Add documentation on how to use sqlalchemy

### PR DESCRIPTION
**Pull request by MichaelDeng03**
- Add mkdoc documentation on sqlalchemy as a developer tool

### CODE REVIEW

**Comment by kgang** [comment]
Omg amazing :)

**Comment by MichaelDeng03** [comment]
any clue where the header buttons for navigating to the pr/diff in slack went?

**Comment by kgang** [comment]
bookmarks. it was better before :disappointed:

**Comment by kgang** [comment]
oh it works on hover? maybe not

**Comment by MichaelDeng03** [comment]
this is pretty clean

**Comment by kgang** [comment]
@abjjabjj take notes

**Comment by abjjabjj** [comment]
lol on the header design?

**Comment by kgang** [comment]
yeah, it's even clickable when the screen becomes smol

**Comment by abjjabjj** [comment]
noted

**Comment by abjjabjj** [comment]
on hover works for me btw

**Comment by kgang** [comment]
yeah it's working for me too, I didn't like it til i discovered that

**Review by abjjabjj — APPROVED** [review]

**Pull request merged**
