### PR TITLE
groqable. definitely needs cleanup, and prompts tailored for groq use.

### PR DESCRIPTION
**Pull request by abjjabjj**

### CODE REVIEW

**Comment by abjjabjj** [comment]
No Assistants API for Groq, so have to go through Chats API

**Comment by kgang** [comment]
Niceu

**Review by MichaelDeng03 — APPROVED** [review]
lgtm

**Comment by kgang** [comment]
Speaking with michael, seems like this isn't working and properly responding to the initial prompt, and it's only seeming to produce relevant code because of our prompt examples

**Comment by abjjabjj** [comment]
Not paying for llama 3.1

**Pull request closed without merging**
